### ISSUE TITLE
Open window detection does not turn off the heat

### ISSUE THREAD

**Issue by s1lviu** [adrianslabu/tado_aa#1]
Hi Adrian,
Thanks for the script! 🇷🇴
It seems that open window detection does not work. The Tado app sends the notification, but the script does not turn off the heat.
Geofencing works ok. 
Thank you!

**Comment by adrianslabu** [comment]
Hi, I just checked it and everything is working, download the script again and retry in case you didn't tried this..

![image](https://user-images.githubusercontent.com/33912486/193281157-c2724b6f-a71d-4ede-baf3-beae46d32ad8.jpeg)

**Comment by s1lviu** [comment]
Thanks, I will further investigate then; the script is the same as it was pulled from here.

**Comment by s1lviu** [comment]
@adrianslabu, yes, I think I forgot how Open Window works. 
I think I need to modify the script a little so that it turns off the heat everywhere, not just in the room with the window open. Thanks for the reply!
