### ISSUE TITLE
PyTado/ Tado(username, password) is printing debug reports

### ISSUE THREAD

**Issue by bjclopes** [adrianslabu/tado_aa#2]
Hello there,

I'm sorry if this is not the right way of reaching out about this issue.
Recently, anytime I run the script, the terminal windows gets a lot of extra debug reports, such as:

"PyTado.http.http :: DEBUG    :: 
Request:
	Method:POST
	URL: https://auth.tado.com/oauth/token<MASKED>
	Headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Referer': 'https://app.tado.com/', 'Content-Length': '2'}
Response:
	StatusCode: ..."

I've tried figuring out how to have these logs hidden, because PyTado has been reworked a bit in the last few months, but I couldn't figure it out. I just know that it happens when we call the Tado(username, password) funcion, associated with PyTado.interface.

Thanks very much for any help and thank you for providing us with this amazing script.

**Comment by adrianslabu** [comment]
Hi, this is not a problem of my script, it's something related to PyTado.
I will commit few changes to fix the "Deprecated" warnings.
