### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by FaserF** [adrianslabu/tado_aa#5]
The script seems to connect and authenticate successfully.
Return code 200

But it seems not to do the automations anymore. Anybody else experiencing this or is this only with my and my friends account?

`Headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Referer': 'https://app.tado.com/', 'Content-Length': '2'}
Response:
	StatusCode: 200
	Data: {<MASKED>, 'token_type': 'bearer', <MASKED>, 'expires_in': 599, 'scope': 'home.user', 'jti': '01526531-8f9d-4d5e-8ccf-f15b17608c4a'}
PyTado.http.http :: DEBUG    :: 
Request:
	Method:POST
	URL: https://auth.tado.com/oauth/token<MASKED>
	Headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Referer': 'https://app.tado.com/', 'Content-Length': '2'}
Response:
	StatusCode: 200
	Data: {<MASKED>, 'token_type': 'bearer', <MASKED>, 'expires_in': 599, 'scope': 'home.user', 'jti': 'fc32f452-9557-4be7-955c-3dc44cbba8e8'}
PyTado.http.http :: DEBUG    :: 
Request:
	Method:POST
	URL: https://auth.tado.com/oauth/token<MASKED>
Headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Referer': 'https://app.tado.com/', 'Content-Length': '2'}
Response:
	StatusCode: 200
	Data: {<MASKED>, 'token_type': 'bearer', <MASKED>, 'expires_in': 599, 'scope': 'home.user', 'jti': '01526531-8f9d-4d5e-8ccf-f15b17608c4a'}
PyTado.http.http :: DEBUG    :: 
Request:
	Method:POST
	URL: https://auth.tado.com/oauth/token<MASKED>
	Headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Referer': 'https://app.tado.com/', 'Content-Length': '2'}
Response:
	StatusCode: 200
	Data: {<MASKED>, 'token_type': 'bearer', <MASKED>, 'expires_in': 599, 'scope': 'home.user', 'jti': 'fc32f452-9557-4be7-955c-3dc44cbba8e8'}
PyTado.http.http :: DEBUG    :: 
Request:
	Method:POST
	URL: https://auth.tado.com/oauth/token<MASKED>
`

**Comment by adrianslabu** [comment]
Hi, everything is working fine, this message is something related with python-tado library. I can't make it disappear but I have in plan to change the script to don't use the python-tado library anymore.
Edit the script and turn on the log by changing enableLog to True. Automations are working fine.
Please check the closed issues next time, this question was asked before.
Thank you and I wish you a warm winter.
