### ISSUE TITLE
Log rotation and relative paths

### ISSUE THREAD

**Issue by James-Oakley** [adrianslabu/tado_aa#7]
Many thanks for this code. I tried turning on log rotation. I'd discovered I needed to put an absolute path for the logFile variable, or I got access denied errors. When the log file filled up and the script tried to rotate the log file into a timestamped archive, I also got permission denied. The directory holding the logs, the directory holding the script itself, and the parent directory to both are all writeable by the user account that runs the script. So I'm guessing it's trying to create the rotated log file somewhere else entirely.

**Comment by adrianslabu** [comment]
Hi, did you tried to run it as root?

**Comment by James-Oakley** [comment]
> Hi, did you tried to run it as root?

Thanks for the suggestion; I'd not thought of trying that. I now have. The log rotation part worked fine; it created the your_log_file_yyyyMMddHHmmss.log file in the working directory I was using at the time. I tried running tado_aa.py with a different working directory open in bash, and the rotated file was again place in my current working directory. I don't know what working directory systemd would use, but I'd guess the script is trying to place a file there (which would need root permissions) rather than in the same directory as the log file it's archiving.
